version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    ports:
    - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
    - 8080:8080
    depends_on:
      - db
